
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='source-query-proxy',
    version='1.4.0',
    description='Async proxy for Source Engine Query Protocol',
    python_requires='==3.*,>=3.7.0',
    project_urls={"homepage": "https://github.com/spumer/source-query-proxy"},
    author='spumer',
    author_email='spumer-tm@yandex.ru',
    license='GPL-3.0',
    keywords='valve source engine proxy query cache',
    entry_points={"console_scripts": ["sqproxy = source_query_proxy.cli:sqproxy"]},
    packages=['source_query_proxy', 'source_query_proxy.source'],
    package_dir={"": "."},
    package_data={},
    install_requires=['async-timeout==3.*,>=3.0.0', 'asyncio-dgram==1.*,>=1.0.0', 'backoff==1.*,>=1.10.0', 'click==7.*,>=7.0.0', 'pid<4.0,>=2.2', 'pydantic[dotenv]==1.*,>=1.4.0', 'pylru==1.*,>=1.2.0', 'pyroute2==0.*,>=0.5.10', 'python-dotenv<0.15.0,>=0.10.3', 'pyyaml==5.*,>=5.2.0', 'sentry-sdk>=0.14.3,<0.20.0', 'uvloop==0.14.0'],
    extras_require={"dev": ["black==19.*,>=19.10.0.b0", "bumpversion==0.*,>=0.5.3", "flake8-awesome==1.*,>=1.2.0", "pytest==6.*,>=6.0.0", "pytest-asyncio==0.*,>=0.14.0", "pytest-cov==2.*,>=2.10.0", "pytest-deadfixtures==2.*,>=2.2.1", "pytest-env==0.*,>=0.6.2", "unify==0.*,>=0.5.0"]},
)
